version: '3'

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - 5432:5432

  api:
    build:
      context: ./
      dockerfile: ./build/Dockerfile.back
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 80:8000
    depends_on:
      - db
  