version: '3'

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  redis:
    image: redis:7.0.8-alpine
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}


  api:
    build:
      context: ./
      dockerfile: ./build/Dockerfile.back
      args:
        - APP_PORT=${APP_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 80:${APP_PORT}
    depends_on:
      - db
  