version: '3'

dotenv: ['.env',]

tasks:
  build_env:
    internal: true
    cmds:
      - cp -n .env.example .env || true
      - ln -sf $(PWD)/.env $(PWD)/website/.env
      - source .env

  run_api:
    dir: './'
    cmds:
      - task: build_env
      - docker-compose up -d db redis
      - swag init -g ./cmd/main/main.go --dir ./ --output ./docs
      - air

  run_front:
    dir: './website'
    cmds:
      - task: build_env
      - echo $PUBLIC_URL
      - PUBLIC_URL=$PUBLIC_URL npm run start

  test_api:
    cmds:
      - task: build_env
      - ENV=test go test ./test/... -count=1 -v

  db_shell:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - docker-compose up -d db && docker-compose exec db psql $POSTGRES_DB -U $POSTGRES_USER

  dropdb:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - docker-compose up -d db 
      - docker-compose exec db psql postgres -U $POSTGRES_USER
        -c "DROP DATABASE IF EXISTS $POSTGRES_DB;"
        -c "CREATE DATABASE $POSTGRES_DB OWNER $POSTGRES_USER;"
      - docker-compose stop db